name: Snapshot release
on:
  push:
    branches: 
      - develop

jobs:
  build:
    name: Publish snpashot version
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Get version
        shell: bash
        run: echo project_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) >> $GITHUB_ENV

      - name: Generate new version
        run: echo new_version=$(./.github/scripts/snapshot-version.sh ${{ env.project_version }}) >> $GITHUB_ENV
        shell: bash

      - name: Show new Maven project version
        run: echo ${{ steps.project.outputs.new_version }}

      - name: Set projects Maven version to GitHub Action GUI set version
        run: mvn versions:set "-DnewVersion=${{ env.new_version }}"

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Push new version to develop branch    
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Snapshot
          tag: '${{ env.new_version }} --force'
